import unittest
import os
import HUELKES_lab2 as l2
class MyTestCase(unittest.TestCase):
    def test_optimize(self):
        optimized = "ATGAGCATTAAAGGCGATAGCCCGAGCAGCACCAACGCGAGCAGCAGCCCGAAAAGCACCTATAGCATTCAGAGCGATGATAAAGCGAACCTGGGCAGCGGCAACGTGGATATTCGCACCGATAACAGCCAGCAGGATAGCAACAACCGCCGCGATATTGTGGTGGTGACCCGCGTGGCGAGCGAAGAAACCCTGGAAAGCCAGAGCAGCACCAGCAGCATGGGCATTCGCCCGGAAAGCAGCTTTAACTATGAAGATGCGAGCAACCAGGCGCGCGTGGAAATGAACAACCGCGTGCATGGCAGCAACATGAACACCATTAACAAATATTATCCGGTGCGCTTTCCGAAAAACAACGAACGCCAGCTGAGCGATACCAACAACCTGAACGAAAAAGTGCAGGGCACCCATACCGTGCAGAGCAGCACCCAGGAAGATAAAATTCTGGATGGCGATACCAGCAACAGCCAGGTGACCCCGAGCCTGAACATTGCGGAATTTCCGACCGATAAACTGCTGAAAATGCTGACCGCGCTGCTGACCAAAATTATTAAAAGCAACGATCGCACCGCGGCGACCAACCCGAGCCTGACCCAGGAAATTGAAAACGGCCGCTGCCTGGCGCTGAGCGATAACGAAAAAAAATATCTGAGCCCGGTGCTGGGCTTTCGCGGCAAACATGTGCCGCAGATTGGCCTGGATCAGTATTTTCAGCGCATTCAGAAATATTGCCCGACCACCAACGATGTGTTTCTGAGCCTGCTGGTGTATTTTGATCGCATTAGCAAACGCTGCAACAGCGTGACCACCACCCCGAAAACCAACACCGCGAAACATGAAAGCCCGAGCAACGAAAGCAGCCTGGATAAAGCGAACCGCGGCGCGGATAAAATGAGCGCGTGCAACAGCAACGAAAACAACGAAAACGATGATAGCGATGATGAAAACACCGGCGTGCAGCGCGATAGCCGCGCGCATCCGCAGATGTTTGTGATGGATAGCCATAACATTCATCGCCTGATTATTGCGGGCATTACCGTGAGCACCAAATTTCTGAGCGATTTTTTTTATAGCAACAGCCGCTATAGCCGCGTGGGCGGCATTAGCCTGCAGGAACTGAACCATCTGGAACTGCAGTTTCTGGTGCTGTGCGATTTTGAACTGCTGATTAGCGTGAACGAACTGCAGCGCTATGCGGATCTGCTGTATCGCTTTTGGAACAACGCGAAAGCGCAGAGCCAGGCGCTGGTGACCGGCATGTAA"
        self.assertEqual(optimized, l2.optimize_gene("YER059W", "Scer.fasta", "Ecol_codon_freqs.csv"))
        self.assertEqual(-1, l2.optimize_gene("ABCDE", "Scer.fasta", "Ecol_codon_freqs.csv"))

        #check file wrote correctly
        self.assertTrue(os.path.exists("YER059W_optimized.fasta"), "Required file does not exist in the working directory.")
        with open("YER059W_optimized.fasta") as file:
            content = file.readlines()
            self.assertEqual(">YER059W", content[0].rstrip())
            self.assertEqual(optimized, content[1].rstrip())

    def test_deoptimize(self):
        deoptimized = "ATGTCAATAAAGGGAGACTCACCCTCATCAACAAATGCTTCATCATCACCCAAGTCAACATACTCAATACAATCAGACGACAAGGCTAATCTAGGATCAGGAAATGTAGACATAAGGACAGACAATTCACAACAAGACTCAAATAATAGGAGGGACATAGTAGTAGTAACAAGGGTAGCTTCAGAGGAGACACTAGAGTCACAATCATCAACATCATCAATGGGAATAAGGCCCGAGTCATCATTCAATTACGAGGACGCTTCAAATCAAGCTAGGGTAGAGATGAATAATAGGGTACACGGATCAAATATGAATACAATAAATAAGTACTACCCCGTAAGGTTCCCCAAGAATAATGAGAGGCAACTATCAGACACAAATAATCTAAATGAGAAGGTACAAGGAACACACACAGTACAATCATCAACACAAGAGGACAAGATACTAGACGGAGACACATCAAATTCACAAGTAACACCCTCACTAAATATAGCTGAGTTCCCCACAGACAAGCTACTAAAGATGCTAACAGCTCTACTAACAAAGATAATAAAGTCAAATGACAGGACAGCTGCTACAAATCCCTCACTAACACAAGAGATAGAGAATGGAAGGTGTCTAGCTCTATCAGACAATGAGAAGAAGTACCTATCACCCGTACTAGGATTCAGGGGAAAGCACGTACCCCAAATAGGACTAGACCAATACTTCCAAAGGATACAAAAGTACTGTCCCACAACAAATGACGTATTCCTATCACTACTAGTATACTTCGACAGGATATCAAAGAGGTGTAATTCAGTAACAACAACACCCAAGACAAATACAGCTAAGCACGAGTCACCCTCAAATGAGTCATCACTAGACAAGGCTAATAGGGGAGCTGACAAGATGTCAGCTTGTAATTCAAATGAGAATAATGAGAATGACGACTCAGACGACGAGAATACAGGAGTACAAAGGGACTCAAGGGCTCACCCCCAAATGTTCGTAATGGACTCACACAATATACACAGGCTAATAATAGCTGGAATAACAGTATCAACAAAGTTCCTATCAGACTTCTTCTACTCAAATTCAAGGTACTCAAGGGTAGGAGGAATATCACTACAAGAGCTAAATCACCTAGAGCTACAATTCCTAGTACTATGTGACTTCGAGCTACTAATATCAGTAAATGAGCTACAAAGGTACGCTGACCTACTATACAGGTTCTGGAATAATGCTAAGGCTCAATCACAAGCTCTAGTAACAGGAATGTAG"
        self.assertEqual(deoptimized, l2.deoptimize_gene("YER059W", "Scer.fasta", "Ecol_codon_freqs.csv"))
        self.assertEqual(-1, l2.deoptimize_gene("ABCDE", "Scer.fasta", "Ecol_codon_freqs.csv"))

        #check file wrote correctly
        self.assertTrue(os.path.exists("YER059W_deoptimized.fasta"), "Required file does not exist in the working directory.")
        with open("YER059W_deoptimized.fasta") as file:
            content = file.readlines()
            self.assertEqual(">YER059W", content[0].rstrip())
            self.assertEqual(deoptimized, content[1].rstrip())


    def test_docstrings(self):
        #test for existance of docstrings
        self.assertFalse(l2.optimize_gene.__doc__ == None)
        self.assertFalse(l2.deoptimize_gene.__doc__ == None)